'''print('\nDiga os números que deseja realizar a conta, o resultado mostrará todas as opções de contas possiveis entre eles')
print('A ordem dos números deverá ser levada em conta para subtração e divisão.')
n1 = float(input('\nPrimeiro número: '))
n2 = float(input('Segundo Número: '))
print(f'A soma dos números é {n1+n2}')
print(f'A subtração dos números é {n1-n2}')
print(f'O produto dos números é {n1*n2}')
print(f'A divisão dos números é {n1/n2}')
print(f'A divisão real dos números é {n1//n2}')
print(f'O restante da divisão dos números é {n1%n2}')
print(f'A exponenciação dos números é {n1**n2}')
print(f'\nO sucessor do Primeiro número é {n1+1} e o antecessor {n1-1}')
print(f'O sucessor do Segundo número é {n2+1} e o antecessor {n2-1}')
print(f'\nO dobro do Primeiro número é {n1*2} e o tplo {n1*3}')
print(f'O dobro do Segundo número é {n2*2} e o triplo {n2*3}')
print(f'\nA raiz quadrado do primeiro número é {n1**(1/2):.3f}')
print(f'A raiz quadrado do segundo número é {n2**(1/2):.3f}')'''
