n = input('Digite algo: ')
print(f'Tipo: {type(n)}')
print(f'É alfanúmerico? {n.isalnum()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É um número? {n.isnumeric()}')
print(f'Está em minusculo? {n.islower()}')
print(f'Está em maisculo? {n.isupper()}')
print(f'Está capitalizada? {n.istitle()}')
print(f'Só tem espaços ? {n.isspace()}')
print(len(n))